// frontend/src/components/base/Etiqueta.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    tono?: 'falta' | 'tipo' | 'ok' | 'mal' | 'atenuado'
    capsula?: boolean
  }>(),
  { tono: 'falta', capsula: false }
)
</script>

<template>
  <span class="etiqueta" :class="[`etiqueta--${tono}`, { 'etiqueta--capsula': capsula }]">
    <slot />
  </span>
</template>

<style scoped>
.etiqueta { font-family: var(--font-ui); white-space: nowrap; }
.etiqueta--falta { color: var(--falta-text); font-size: var(--fs-125); }
.etiqueta--tipo {
  color: var(--text-link); font-size: var(--fs-11); font-weight: var(--fw-bold);
  letter-spacing: var(--ls-caps); text-transform: uppercase;
}
.etiqueta--ok { color: var(--ok); font-size: var(--fs-135); font-weight: var(--fw-semibold); }
.etiqueta--mal { color: var(--bad); font-size: var(--fs-135); font-weight: var(--fw-semibold); }
.etiqueta--atenuado { color: var(--text-muted); font-size: var(--fs-125); }
.etiqueta--capsula { background: var(--surface-sunken); border-radius: var(--radio-pill); padding: 2px 8px; }
</style>

// .claude/skills/anpael-design/components/base/Etiqueta.jsx
import React from 'react';

const tonos = {
  falta: { color: 'var(--falta-text)', fontSize: 'var(--fs-125)' },
  tipo: {
    color: 'var(--text-link)',
    fontSize: 'var(--fs-11)',
    fontWeight: 'var(--fw-bold)',
    letterSpacing: 'var(--ls-caps)',
    textTransform: 'uppercase',
  },
  ok: { color: 'var(--ok)', fontSize: 'var(--fs-135)', fontWeight: 'var(--fw-semibold)' },
  mal: { color: 'var(--bad)', fontSize: 'var(--fs-135)', fontWeight: 'var(--fw-semibold)' },
  atenuado: { color: 'var(--text-muted)', fontSize: 'var(--fs-125)' },
};

export function Etiqueta({ tono = 'falta', capsula = false, children, style, ...resto }) {
  const t = tonos[tono] || tonos.falta;
  return (
    <span
      style={{
        fontFamily: 'var(--font-ui)',
        whiteSpace: 'nowrap',
        ...t,
        ...(capsula ? { background: 'var(--surface-sunken)', borderRadius: 'var(--radio-pill)', padding: '2px 8px' } : null),
        ...style,
      }}
      {...resto}
    >
      {children}
    </span>
  );
}
