// .claude/skills/anpael-design/components/formularios/Check.jsx
import React from 'react';

export function Check({ etiqueta, marcado, onChange, deshabilitado = false, style, ...resto }) {
  return (
    <label
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        font: 'var(--text-label)',
        color: 'var(--text-muted)',
        cursor: deshabilitado ? 'not-allowed' : 'pointer',
        opacity: deshabilitado ? 0.5 : 1,
        ...style,
      }}
    >
      <input
        type="checkbox"
        checked={marcado}
        onChange={onChange}
        disabled={deshabilitado}
        style={{ accentColor: 'var(--pasto-700)', width: 15, height: 15, margin: 0 }}
        {...resto}
      />
      {etiqueta}
    </label>
  );
}

// frontend/src/components/formularios/Check.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    etiqueta?: string
    marcado?: boolean
    deshabilitado?: boolean
  }>(),
  { marcado: false, deshabilitado: false }
)

defineEmits<{ 'update:marcado': [marcado: boolean] }>()
</script>

<template>
  <label class="check" :class="{ 'check--deshabilitado': deshabilitado }">
    <input
      type="checkbox"
      class="check-input"
      :checked="marcado"
      :disabled="deshabilitado"
      @change="$emit('update:marcado', ($event.target as HTMLInputElement).checked)"
    />
    {{ etiqueta }}
  </label>
</template>

<style scoped>
.check {
  display: flex;
  align-items: center;
  gap: 6px;
  font: var(--text-label);
  color: var(--text-muted);
  cursor: pointer;
}
.check--deshabilitado { cursor: not-allowed; opacity: .5; }
.check-input { accent-color: var(--pasto-700); width: 15px; height: 15px; margin: 0; }
</style>
