// frontend/src/components/datos/Paginado.vue
<script setup lang="ts">
import Boton from '@/components/base/Boton.vue'

const props = withDefaults(
  defineProps<{
    pagina?: number
    totalPaginas?: number
  }>(),
  { pagina: 0, totalPaginas: 1 }
)

const emit = defineEmits<{ cambio: [pagina: number] }>()
</script>

<template>
  <nav v-if="totalPaginas > 1" class="paginado">
    <Boton variante="sobrio" tamano="sm" :deshabilitado="pagina === 0" @click="emit('cambio', pagina - 1)">
      ‹ Anterior
    </Boton>
    <span class="paginado-texto">pagina {{ props.pagina + 1 }} de {{ props.totalPaginas }}</span>
    <Boton
      variante="sobrio"
      tamano="sm"
      :deshabilitado="pagina >= totalPaginas - 1"
      @click="emit('cambio', pagina + 1)"
    >
      Siguiente ›
    </Boton>
  </nav>
</template>

<style scoped>
.paginado { display: flex; align-items: center; justify-content: center; gap: 16px; margin-top: 16px; }
.paginado-texto { color: var(--text-muted); font-family: var(--font-ui); font-size: var(--fs-13); }
</style>

// .claude/skills/anpael-design/components/datos/Paginado.jsx
import React from 'react';
import { Boton } from '../base/Boton.jsx';

export function Paginado({ pagina = 0, totalPaginas = 1, onCambio, style, ...resto }) {
  if (totalPaginas <= 1) return null;
  return (
    <nav
      style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 16, marginTop: 16, ...style }}
      {...resto}
    >
      <Boton variante="sobrio" tamano="sm" deshabilitado={pagina === 0} onClick={() => onCambio && onCambio(pagina - 1)}>
        {'\u2039'} Anterior
      </Boton>
      <span style={{ color: 'var(--text-muted)', fontFamily: 'var(--font-ui)', fontSize: 'var(--fs-13)' }}>
        pagina {pagina + 1} de {totalPaginas}
      </span>
      <Boton
        variante="sobrio"
        tamano="sm"
        deshabilitado={pagina >= totalPaginas - 1}
        onClick={() => onCambio && onCambio(pagina + 1)}
      >
        Siguiente {'\u203A'}
      </Boton>
    </nav>
  );
}
