// .claude/skills/anpael-design/components/base/Tarjeta.jsx
import React from 'react';

export function Tarjeta({ titulo, nota, denso = false, children, style, ...resto }) {
  return (
    <section
      style={{
        background: 'var(--surface-card)',
        border: 'var(--borde-fino)',
        borderRadius: 'var(--radio-lg)',
        padding: denso ? 'var(--pad-tarjeta-tabla)' : 'var(--pad-tarjeta)',
        color: 'var(--text-body)',
        font: 'var(--text-base)',
        ...style,
      }}
      {...resto}
    >
      {titulo ? (
        <h3 style={{ margin: nota ? '0 0 4px' : '0 0 12px', font: 'var(--text-h3)' }}>{titulo}</h3>
      ) : null}
      {nota ? (
        <p style={{ margin: '0 0 12px', font: 'var(--text-caption)', color: 'var(--text-muted)' }}>{nota}</p>
      ) : null}
      {children}
    </section>
  );
}

// frontend/src/components/base/Tarjeta.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    titulo?: string
    nota?: string
    denso?: boolean
  }>(),
  { denso: false }
)
</script>

<template>
  <section class="tarjeta" :class="{ 'tarjeta--densa': denso }">
    <h3 v-if="titulo" class="tarjeta-titulo" :class="{ 'tarjeta-titulo--con-nota': nota }">{{ titulo }}</h3>
    <p v-if="nota" class="tarjeta-nota">{{ nota }}</p>
    <slot />
  </section>
</template>

<style scoped>
.tarjeta {
  background: var(--surface-card);
  border: var(--borde-fino);
  border-radius: var(--radio-lg);
  padding: var(--pad-tarjeta);
  color: var(--text-body);
  font: var(--text-base);
}
.tarjeta--densa { padding: var(--pad-tarjeta-tabla); }
.tarjeta-titulo { margin: 0 0 12px; font: var(--text-h3); }
.tarjeta-titulo--con-nota { margin: 0 0 4px; }
.tarjeta-nota { margin: 0 0 12px; font: var(--text-caption); color: var(--text-muted); }
</style>
