// frontend/src/components/avisos/Aviso.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    tono?: 'ok' | 'error' | 'atencion' | 'info'
    detalle?: string
  }>(),
  { tono: 'info' }
)
</script>

<template>
  <p class="aviso" :class="`aviso--${tono}`" :role="tono === 'error' ? 'alert' : undefined">
    <slot />
    <span v-if="detalle" class="aviso-detalle"> — {{ detalle }}</span>
  </p>
</template>

<style scoped>
.aviso {
  border-style: solid;
  border-width: 1px;
  border-radius: var(--radio-md);
  padding: 10px;
  font-family: var(--font-ui);
  font-size: var(--fs-13);
  line-height: var(--lh-normal);
  margin: 0;
}
.aviso--ok { background: var(--ok-bg); border-color: var(--ok-border); color: var(--ok-text); }
.aviso--error { background: var(--bad-bg); border-color: var(--bad-border); color: var(--bad-text); }
.aviso--atencion { background: var(--warn-bg); border-color: var(--warn-border); color: var(--warn-text); }
.aviso--info { background: var(--info-bg); border-color: var(--info-border); color: var(--info-text); }
.aviso-detalle { opacity: .8; }
</style>

// .claude/skills/anpael-design/components/avisos/Aviso.jsx
import React from 'react';

const tonos = {
  ok: { background: 'var(--ok-bg)', borderColor: 'var(--ok-border)', color: 'var(--ok-text)' },
  error: { background: 'var(--bad-bg)', borderColor: 'var(--bad-border)', color: 'var(--bad-text)' },
  atencion: { background: 'var(--warn-bg)', borderColor: 'var(--warn-border)', color: 'var(--warn-text)' },
  info: { background: 'var(--info-bg)', borderColor: 'var(--info-border)', color: 'var(--info-text)' },
};

export function Aviso({ tono = 'info', detalle, children, style, ...resto }) {
  const t = tonos[tono] || tonos.info;
  return (
    <p
      role={tono === 'error' ? 'alert' : undefined}
      style={{
        borderStyle: 'solid',
        borderWidth: 1,
        borderRadius: 'var(--radio-md)',
        padding: '10px',
        fontFamily: 'var(--font-ui)',
        fontSize: 'var(--fs-13)',
        lineHeight: 'var(--lh-normal)',
        margin: 0,
        ...t,
        ...style,
      }}
      {...resto}
    >
      {children}
      {detalle ? <span style={{ opacity: 0.8 }}> {'\u2014'} {detalle}</span> : null}
    </p>
  );
}
